<script lang="ts">
  import geminiLogo from "/gemini.svg";
  import { marked } from "marked";
  export let message, hours;
</script>

<div class="flex items-start gap-2.5 py-2">
  <img
    class="w-8 h-8 rounded-full"
    src={geminiLogo}
    alt="Jese image"
    aria-hidden="true"
  />
  <div
    class="flex flex-col w-full max-w-[1440px] leading-1.5 p-4 border-gray-200 bg-gray-100 rounded-e-xl rounded-es-xl dark:bg-gray-700"
  >
    <div class="flex items-center space-x-2 rtl:space-x-reverse">
      <span class="text-sm font-semibold text-gray-900 dark:text-white"
        >Modularity</span
      >
      <span class="text-sm font-normal text-gray-500 dark:text-gray-400"
        >{hours}</span
      >
    </div>
    <p class="text-sm font-normal py-2.5 text-gray-900 dark:text-white">
      {@html marked(message)}
    </p>
    <span class="text-sm font-normal text-gray-500 dark:text-gray-400"
      >Generated by Gemini Nano</span
    >
  </div>
</div>
